### ISSUE TITLE
tensorflow listed in requirements.txt

### ISSUE THREAD

**Issue by gar1t** [iitzco/tfserve#2]
By listing the `tensorflow` package as a requirement the package installs the non GPU package.

This is a problem for any TensorFlow library. I think the right approach is to remove that package from the list and require the user to install it.

Anyone using tfserve will surely be okay dealing with TensorFlow installation as a pre-req.

Another approach would be to ship two packages: `tfserve` and `tfserve-gpu` (e.g. the Magenta project does this). But I think that's far more painful all around than just omitting the requirement.

**Comment by iitzco** [comment]
Totally agree on this one.

I wonder if it's possible to detect automatically wether `tensorflow` or `tensorflow-gpu` must be installed while installing dependencies when running `pip install tfserve`. @gar1t do you know any possible solution?

If there is not such solution, then we could remove it from `requirements.txt` and ask the user to install it, just as you proposed. Or leave `tensorflow` as default and specify the user with GPU to just run `pip uninstall tensorflow && pip install tensorflow-gpu`

**Comment by iitzco** [comment]
`tfserve` and `tfserve-gpu` would be ideal but I currently don't have the time to implement it. PRs are welcome obviously!

**Comment by gar1t** [comment]
Yeah, everyone doing TensorFlow libraries has the same problem unfortunately. Even stuff from Google leaks this requirements, which causes mysterious env breakage for anyone using tensorflow-gpu.

Doing two packages technically fixes the breakage problem at one level, but simply shifts the burden to your downstream users - so then everyone in the universe touching tensorflow has the two package problem!

Yep, I'll get you a PR for this :)
