### ISSUE TITLE
Severe breakage with apistar 0.6

### ISSUE THREAD

**Issue by gar1t** [iitzco/tfserve#3]
apistar has been overhauled for 0.6 to be CLI only.

https://github.com/encode/apistar/pull/624

The server support that tfserve relies on is gone :(

**Comment by iitzco** [comment]
Good catch. I was unaware of this.

I will take a look at [Starlette](https://www.starlette.io/) (which is APIStar's recommendation). If not, I will migrate to flask.

For now, I think we can use `apistar==0.5.41` as mentioned [here](https://github.com/encode/apistar#what-did-the-server-go).

**Comment by gar1t** [comment]
From the functionality I'm seeing in tfserve, I think using Werkzeug directly may work fine. I can put together a PR for you to look at as an option.

**Comment by iitzco** [comment]
Werkzeug is now the default server framework. Thanks @gar1t for the PR!

**Comment by kjodha** [comment]
@gar1t @iitzco I'd like to send the prediction response as bytes and not as json, is there a way to do that here?
